on: [push]

jobs:
  balena-push:
    runs-on: ubuntu-latest
    name: Push changes to balenaCloud
    steps:
    - name: Push action step
      id: push
      uses: balena-io-playground/balena-cloud-github-action@v0.1
      with:
        balena-token: 'abcde12345'
        balena-app-name: 'python-hello-world'
    - name: Get the release
      run: echo "New release created ${{ steps.push.outputs.release }}"
